SET LINES 999 PAGES 999
COL MB FORMAT 999999
COL NAME FORMAT A100

SELECT  NAME FROM V$DATAFILE
UNION ALL
SELECT  NAME FROM V$TEMPFILE
UNION ALL
SELECT  MEMBER AS NAME FROM V$LOG L, V$LOGFILE F  WHERE F.GROUP# = L.GROUP#
UNION ALL
SELECT  NAME FROM V$CONTROLFILE
UNION ALL
SELECT FILENAME AS NAME FROM V$BLOCK_CHANGE_TRACKING;